[versions]
kotlin = "2.1.21"

# trying-kotlin module configuration information
tryingKotlin-group = "com.trying.kotlin"
version = "1.0.0"

[libraries]

[plugins]
kotlin-compiler = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }